@baseURL = http://localhost:{{$dotenv PORT}}

### LOGIN
POST {{baseURL}}/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "denis@gmail.com",
    "password": "test"
}

### REGISTER
POST {{baseURL}}/auth/register
Content-Type: application/json
Accept: application/json

{
    "name": "denis",
    "surname": "cerri",
    "email": "denis@gmail.com",
    "password": "test"
}

### LOGOUT
POST {{baseURL}}/auth/logout

### GET USER INFO
GET {{baseURL}}/user/info

### UPDATE USER INFO
PATCH {{baseURL}}/user/info
Content-Type: application/json
Accept: application/json

{
    "name": "denis",
    "surname": "cerri",
    "email": "denis@gmail.com",
    "gender": "Male",
    "birthday": "2000-05-17"
}


### UPDATE PASSWORD
PATCH {{baseURL}}/user/password
Content-Type: application/json
Accept: application/json

{
    "password": "test2"
}

### GET ADDRESSES
GET {{baseURL}}/addresses

### CREATE ADDRESS
POST {{baseURL}}/addresses/create
Content-Type: application/json

{
    "name": "Denis",
    "surname": "Çerri",
    "email": "denis@gmail.com",
    "country": "Albania",
    "city": "Elbasan",
    "line1": "Posta 3001",
    "line2": "Pallati 1212321412",
    "phone": "+3551111111"
}

### UPDATE ADDRESS
PATCH {{baseURL}}/addresses/update/2
Content-Type: application/json
Accept: application/json

{
    "name": "Denis",
    "surname": "Çerri",
    "email": "denis@gmail.com",
    "country": "Albania",
    "city": "Tirana",
    "line1": "Posta 3001",
    "line2": "Pallati 1212321412",
    "phone": "+3552222222"
}

### DELETE ADDRESS
DELETE {{baseURL}}/addresses/1

### GET ORDERS
GET {{baseURL}}/orders

### MAKE ORDER
POST {{baseURL}}/orders/create
Content-Type: application/json

{
    "address_id": 1,
    "products": [1,2]
}

### UPDATE ORDER
PATCH {{baseURL}}/orders/update/1
Content-Type: application/json

{
    "address_id": 2,
    "shipping_date": "2022-12-25",
    "status": "Accepted"
}

### DELETE ORDER
DELETE {{baseURL}}/orders/1

### GET ALL USERS
GET {{baseURL}}/user/all

### CREATE USER
POST {{baseURL}}/user/create
Content-Type: application/json

{
    "name": "sined",
    "surname": "irrec",
    "email": "sined@gmail.com",
    "password": "test",
    "type": "admin"
}


### GET PRODUCTS
GET {{baseURL}}/products?page=1&size=5

### GET PRODUCTS BY CATEGORY
GET {{baseURL}}/products/category/phone?page=3&size=5

### GET PRODUCT BY ID
GET {{baseURL}}/products/1

### CREATE PRODUCT
POST {{baseURL}}/products/create
Content-Type: application/json

{
    "name": "Iphone",
    "description": "this is a phone",
    "price": 750,
    "discounted_price": 700,
    "stock": 22,
    "category": "phone",
    "images": [
        "https://3vfejzo.shop/wp-content/uploads/2022/10/Apple-iPhone-14-Pro-iPhone-14-Pro-Max-silver-220907_inline.jpg.large_.jpeg",
        "https://www.apple.com/v/iphone-14-pro/c/images/meta/iphone-14-pro_overview__e414c54gtu6a_og.png",
        "https://www.redline.al/wp-content/uploads/2022/09/Apple-iPhone-14-Pro-iPhone-14-Pro-Max-deep-purple-220907_inline.jpg.large_.jpg"
    ]
}

### UPDATE PRODUCT
PATCH {{baseURL}}/products/3
Content-Type: application/json
Accept: application/json

{
    "name": "Gaming PC",
    "description": "this is a pc",
    "price": 850,
    "discounted_price": 800,
    "stock": 69,
    "category": "computer",
    "images": [
        "https://m.media-amazon.com/images/I/819XYUimTuL.jpg",
        "https://m.media-amazon.com/images/I/91LSF1iZUFL.jpg",
        "https://m.media-amazon.com/images/I/81gqqKQVkAL.jpg"
    ]
}

### DELETE PRODUCT
DELETE {{baseURL}}/products/3